ALTER TABLE waves ADD COLUMN avg_path_progress REAL NOT NULL DEFAULT 0;
ALTER TABLE waves ADD COLUMN max_path_progress REAL NOT NULL DEFAULT 0;
ALTER TABLE waves ADD COLUMN avg_ticks_to_kill REAL NOT NULL DEFAULT 0;
